// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQIAfGCRC0DI5FUINaNBn32B-Xq5ix4Mk',
    appId: '1:802835357463:android:40f0988675cc6ca6c66152',
    messagingSenderId: '802835357463',
    projectId: 'fyp-makeup-artist-booking',
    databaseURL: 'https://fyp-makeup-artist-booking-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp-makeup-artist-booking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEN6ciHjR9hMeHjMva8996aHihTVN0BHo',
    appId: '1:802835357463:ios:24d59ca3af157795c66152',
    messagingSenderId: '802835357463',
    projectId: 'fyp-makeup-artist-booking',
    databaseURL: 'https://fyp-makeup-artist-booking-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp-makeup-artist-booking.firebasestorage.app',
    iosBundleId: 'com.example.blushUp',
  );

}